# Generated by Django 2.0.7 on 2019-05-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='promission',
            new_name='promissions',
        ),
    ]
