# Generated by Django 2.1.5 on 2019-05-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190503_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
